name: Weekly

on:
  schedule:
    - cron: '0 0 * * 1' # Run weekly
  workflow_dispatch:

jobs:
  cron_job:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v3
      - uses: Mattraks/delete-workflow-runs@v2
      - uses: gautamkrishnar/keepalive-workflow@v1
        with:
          commit_message: 'keep alive auto-commit'
          committer_username: 'github-actions[bot]'
          committer_email: 'github-actions[bot]@users.noreply.github.com'
          time_elapsed: 50

  # keep_alive:
  #   uses: WaterLemons2k/scheduled-workflow-activity-action/.github/workflows/reusable.yml@v1
  #   with:
  #     days: 30
  #     message: 'keep alive auto-commit'
