name: Weekly

on:
  schedule:
    - cron: '0 0 * * 1' # Run weekly
  workflow_dispatch:
permissions:
  contents: write

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Keepalive check
        uses: gautamkrishnar/keepalive-workflow@v1
        with:
          commit_message: 'keep alive auto-commit'
          committer_username: 'github-actions[bot]'
          committer_email: 'github-actions[bot]@users.noreply.github.com'
          time_elapsed: 50
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        continue-on-error: true

  # keep_alive:
  #   uses: WaterLemons2k/scheduled-workflow-activity-action/.github/workflows/reusable.yml@v1
  #   with:
  #     days: 30
  #     message: 'keep alive auto-commit'
